# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(347, 553)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbFlags = QtWidgets.QGroupBox(OptionsDialog)
        self.gbFlags.setObjectName("gbFlags")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbFlags)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbReadOnly = QtWidgets.QCheckBox(self.gbFlags)
        self.cbReadOnly.setObjectName("cbReadOnly")
        self.gridLayout_2.addWidget(self.cbReadOnly, 3, 0, 1, 1)
        self.cbHighlighting = QtWidgets.QCheckBox(self.gbFlags)
        self.cbHighlighting.setObjectName("cbHighlighting")
        self.gridLayout_2.addWidget(self.cbHighlighting, 2, 0, 1, 1)
        self.cbOverwriteMode = QtWidgets.QCheckBox(self.gbFlags)
        self.cbOverwriteMode.setObjectName("cbOverwriteMode")
        self.gridLayout_2.addWidget(self.cbOverwriteMode, 1, 0, 1, 1)
        self.cbAddressArea = QtWidgets.QCheckBox(self.gbFlags)
        self.cbAddressArea.setObjectName("cbAddressArea")
        self.gridLayout_2.addWidget(self.cbAddressArea, 1, 1, 1, 1)
        self.cbAsciiArea = QtWidgets.QCheckBox(self.gbFlags)
        self.cbAsciiArea.setObjectName("cbAsciiArea")
        self.gridLayout_2.addWidget(self.cbAsciiArea, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbFlags)
        self.gbColors = QtWidgets.QGroupBox(OptionsDialog)
        self.gbColors.setObjectName("gbColors")
        self.gridLayout = QtWidgets.QGridLayout(self.gbColors)
        self.gridLayout.setObjectName("gridLayout")
        self.pbHighlightingColor = QtWidgets.QPushButton(self.gbColors)
        self.pbHighlightingColor.setObjectName("pbHighlightingColor")
        self.gridLayout.addWidget(self.pbHighlightingColor, 0, 0, 1, 1)
        self.lbHighlightingColor = QtWidgets.QLabel(self.gbColors)
        self.lbHighlightingColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbHighlightingColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbHighlightingColor.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbHighlightingColor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbHighlightingColor.setText("")
        self.lbHighlightingColor.setObjectName("lbHighlightingColor")
        self.gridLayout.addWidget(self.lbHighlightingColor, 0, 1, 1, 1)
        self.pbAddressAreaColor = QtWidgets.QPushButton(self.gbColors)
        self.pbAddressAreaColor.setObjectName("pbAddressAreaColor")
        self.gridLayout.addWidget(self.pbAddressAreaColor, 1, 0, 2, 1)
        self.lbAddressAreaColor = QtWidgets.QLabel(self.gbColors)
        self.lbAddressAreaColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbAddressAreaColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbAddressAreaColor.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbAddressAreaColor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbAddressAreaColor.setText("")
        self.lbAddressAreaColor.setObjectName("lbAddressAreaColor")
        self.gridLayout.addWidget(self.lbAddressAreaColor, 1, 1, 2, 1)
        self.lbSelectionColor = QtWidgets.QLabel(self.gbColors)
        self.lbSelectionColor.setMinimumSize(QtCore.QSize(100, 0))
        self.lbSelectionColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbSelectionColor.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbSelectionColor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbSelectionColor.setText("")
        self.lbSelectionColor.setObjectName("lbSelectionColor")
        self.gridLayout.addWidget(self.lbSelectionColor, 3, 1, 1, 1)
        self.pbSelectionColor = QtWidgets.QPushButton(self.gbColors)
        self.pbSelectionColor.setObjectName("pbSelectionColor")
        self.gridLayout.addWidget(self.pbSelectionColor, 3, 0, 1, 1)
        self.pbWidgetFont = QtWidgets.QPushButton(self.gbColors)
        self.pbWidgetFont.setObjectName("pbWidgetFont")
        self.gridLayout.addWidget(self.pbWidgetFont, 4, 0, 1, 1)
        self.leWidgetFont = QtWidgets.QLineEdit(self.gbColors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leWidgetFont.sizePolicy().hasHeightForWidth())
        self.leWidgetFont.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.leWidgetFont.setFont(font)
        self.leWidgetFont.setObjectName("leWidgetFont")
        self.gridLayout.addWidget(self.leWidgetFont, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbColors)
        self.gbAddressAreaWidth = QtWidgets.QGroupBox(OptionsDialog)
        self.gbAddressAreaWidth.setObjectName("gbAddressAreaWidth")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbAddressAreaWidth)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbAddressAreaWidth = QtWidgets.QLabel(self.gbAddressAreaWidth)
        self.lbAddressAreaWidth.setObjectName("lbAddressAreaWidth")
        self.gridLayout_3.addWidget(self.lbAddressAreaWidth, 0, 0, 1, 1)
        self.sbAddressAreaWidth = QtWidgets.QSpinBox(self.gbAddressAreaWidth)
        self.sbAddressAreaWidth.setMinimum(3)
        self.sbAddressAreaWidth.setMaximum(8)
        self.sbAddressAreaWidth.setProperty("value", 4)
        self.sbAddressAreaWidth.setObjectName("sbAddressAreaWidth")
        self.gridLayout_3.addWidget(self.sbAddressAreaWidth, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbAddressAreaWidth)
        self.gbHexArea = QtWidgets.QGroupBox(OptionsDialog)
        self.gbHexArea.setObjectName("gbHexArea")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbHexArea)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbBytesPerLine = QtWidgets.QLabel(self.gbHexArea)
        self.lbBytesPerLine.setObjectName("lbBytesPerLine")
        self.gridLayout_4.addWidget(self.lbBytesPerLine, 0, 0, 1, 1)
        self.sbBytesPerLine = QtWidgets.QSpinBox(self.gbHexArea)
        self.sbBytesPerLine.setMinimum(8)
        self.sbBytesPerLine.setMaximum(32)
        self.sbBytesPerLine.setProperty("value", 16)
        self.sbBytesPerLine.setSingleStep(8)
        self.sbBytesPerLine.setObjectName("sbBytesPerLine")
        self.gridLayout_4.addWidget(self.sbBytesPerLine, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbHexArea)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.buttonBox.accepted.connect(OptionsDialog.accept)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)
        OptionsDialog.setTabOrder(self.pbHighlightingColor, self.pbAddressAreaColor)
        OptionsDialog.setTabOrder(self.pbAddressAreaColor, self.buttonBox)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "QHexEdit - Options"))
        self.gbFlags.setTitle(_translate("OptionsDialog", "Flags"))
        self.cbReadOnly.setText(_translate("OptionsDialog", "ReadOnly"))
        self.cbHighlighting.setText(_translate("OptionsDialog", "Higlighting"))
        self.cbOverwriteMode.setText(_translate("OptionsDialog", "Overwrite Mode"))
        self.cbAddressArea.setText(_translate("OptionsDialog", "Address Area"))
        self.cbAsciiArea.setText(_translate("OptionsDialog", "Ascii Area"))
        self.gbColors.setTitle(_translate("OptionsDialog", "Colors and Fonts"))
        self.pbHighlightingColor.setText(_translate("OptionsDialog", "Highlighting Color"))
        self.pbAddressAreaColor.setText(_translate("OptionsDialog", "Address Area Color"))
        self.pbSelectionColor.setText(_translate("OptionsDialog", "Selection Color"))
        self.pbWidgetFont.setText(_translate("OptionsDialog", "Widget Font"))
        self.leWidgetFont.setText(_translate("OptionsDialog", "01 23 45 67 89 ab cd ef"))
        self.gbAddressAreaWidth.setTitle(_translate("OptionsDialog", "Address Area"))
        self.lbAddressAreaWidth.setText(_translate("OptionsDialog", "Address Area Width"))
        self.gbHexArea.setTitle(_translate("OptionsDialog", "Hex Area"))
        self.lbBytesPerLine.setText(_translate("OptionsDialog", "Bytes per Line"))
